### ISSUE TITLE
Diseño De Interactividad De La Realidad Aumentada

### ISSUE THREAD

**Issue by ArteezyOne** [SistemasTecTlaxiaco/diseno-de-interactividad-de-la-realidad-aumentada-joel#1]
[Diseño De Interactividad De La Realidad Aumentada.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-interactividad-de-la-realidad-aumentada-joel/files/6385074/Diseno.De.Interactividad.De.La.Realidad.Aumentada.pdf)

**Comment by Itzelzun** [comment]
Calificación 20

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
